development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: remitano_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: remitano_production
